<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_post2</name>
   <tag></tag>
   <elementGuidId>61b11e91-436f-4d36-8a19-3f7459ba3918</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.title.is-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[4]/div/div/a/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;post2&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>1a1a6b01-bf3b-4433-96f1-f966a24cd91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title is-5</value>
      <webElementGuid>55e4f1df-d6dd-4857-b1c6-ce6ba6e4af04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>post2</value>
      <webElementGuid>344758d4-72e9-4c14-8d8a-368e1be6d0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-container&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;column m-5 is-two-thirds&quot;]/div[@class=&quot;app-container&quot;]/div[@class=&quot;box&quot;]/div[1]/div[@class=&quot;box&quot;]/a[1]/h4[@class=&quot;title is-5&quot;]</value>
      <webElementGuid>de64420f-f890-4e6e-8fe7-a2f038883ac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[4]/div/div/a/h4</value>
      <webElementGuid>06c52a45-95b7-48f0-a76d-5af041c2fd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Posts'])[1]/following::h4[1]</value>
      <webElementGuid>ef5a016d-11f9-478b-a856-1d4bd010d204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Post'])[1]/following::h4[1]</value>
      <webElementGuid>b22aa9c1-b02a-46e8-83df-4a2323d5335b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#tag5'])[1]/preceding::h4[1]</value>
      <webElementGuid>2fa17361-9a54-40fb-87e5-eb90df298c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#tag8'])[1]/preceding::h4[1]</value>
      <webElementGuid>08d20971-c260-4a4d-9842-93faaef30a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='post2']/parent::*</value>
      <webElementGuid>26d58d79-92ad-4106-a865-468398776065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>1b3496c8-3512-43b6-b1c5-53a8929b6000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'post2' or . = 'post2')]</value>
      <webElementGuid>a2c5dbe1-becf-4e56-8ff8-c88994244dc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
