<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , webpack-dev-server-cli_baf6c8</name>
   <tag></tag>
   <elementGuidId>f8c97a11-30e6-400a-a799-f83ee09844bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#webpack-dev-server-client-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='webpack-dev-server-client-overlay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#webpack-dev-server-client-overlay</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fa5e3a94-2eb4-4bed-bede-143f12b73ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>webpack-dev-server-client-overlay</value>
      <webElementGuid>6dd1397e-4e70-4b9d-9324-b0602e075151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>c8a99c30-44a5-4751-893e-8b8eff117a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webpack-dev-server-client-overlay&quot;)</value>
      <webElementGuid>d5feebe1-6718-40ff-aad5-b1b5c9a09cdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='webpack-dev-server-client-overlay']</value>
      <webElementGuid>dfbefb71-e225-494f-9809-a02c48aeff4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e92ea522-9c74-4db1-a447-1623d62ed35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'webpack-dev-server-client-overlay' and @src = 'about:blank']</value>
      <webElementGuid>fad2747b-820e-4021-8d9b-27043ccfeccf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
